# Data cleaning  &Pre Processing

In [2]:
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
import warnings
warnings.filterwarnings("ignore")

In [5]:
df = pd.read_csv("insurance (1).csv")
df

      age     sex   bmi  children smoker     region  expenses
0      19  female  27.9         0    yes  southwest  16884.92
1      18    male  33.8         1     no  southeast   1725.55
2      28    male  33.0         3     no  southeast   4449.46
3      33    male  22.7         0     no  northwest  21984.47
4      32    male  28.9         0     no  northwest   3866.86
...   ...     ...   ...       ...    ...        ...       ...
1333   50    male  31.0         3     no  northwest  10600.55
1334   18  female  31.9         0     no  northeast   2205.98
1335   18  female  36.9         0     no  southeast   1629.83
1336   21  female  25.8         0     no  southwest   2007.95
1337   61  female  29.1         0    yes  northwest  29141.36

[1338 rows x 7 columns]

In [6]:
df.head()

   age     sex   bmi  children smoker     region  expenses
0   19  female  27.9         0    yes  southwest  16884.92
1   18    male  33.8         1     no  southeast   1725.55
2   28    male  33.0         3     no  southeast   4449.46
3   33    male  22.7         0     no  northwest  21984.47
4   32    male  28.9         0     no  northwest   3866.86

In [7]:
df.shape

(1338, 7)

In [8]:
df.isnull().sum()

age         0
sex         0
bmi         0
children    0
smoker      0
region      0
expenses    0
dtype: int64

In [9]:
df.drop_duplicates(inplace=True)
df.shape

(1337, 7)

In [10]:
df.dtypes

age           int64
sex             str
bmi         float64
children      int64
smoker          str
region          str
expenses    float64
dtype: object

In [11]:
df['sex'].unique()

<ArrowStringArray>
['female', 'male']
Length: 2, dtype: str

In [12]:
#convert str to int
#labeled encoding
df['sex']= df["sex"].map({"male":0 , "female": 1})

In [13]:
df.dtypes

age           int64
sex           int64
bmi         float64
children      int64
smoker          str
region          str
expenses    float64
dtype: object

In [14]:
df.head()

   age  sex   bmi  children smoker     region  expenses
0   19    1  27.9         0    yes  southwest  16884.92
1   18    0  33.8         1     no  southeast   1725.55
2   28    0  33.0         3     no  southeast   4449.46
3   33    0  22.7         0     no  northwest  21984.47
4   32    0  28.9         0     no  northwest   3866.86

In [15]:
df['smoker'].unique()

<ArrowStringArray>
['yes', 'no']
Length: 2, dtype: str

In [16]:
df['smoker'].value_counts()

smoker
no     1063
yes     274
Name: count, dtype: int64

In [17]:
df['smoker']= df['smoker'].map({'yes':1,'no':0}) #object to number
df.dtypes

age           int64
sex           int64
bmi         float64
children      int64
smoker        int64
region          str
expenses    float64
dtype: object

In [18]:
df.head()

   age  sex   bmi  children  smoker     region  expenses
0   19    1  27.9         0       1  southwest  16884.92
1   18    0  33.8         1       0  southeast   1725.55
2   28    0  33.0         3       0  southeast   4449.46
3   33    0  22.7         0       0  northwest  21984.47
4   32    0  28.9         0       0  northwest   3866.86

In [19]:
#rename column
df.rename(columns={
    'sex': "is_female",
    'smoker':"is_smoker"
},inplace=True)

In [20]:
df

      age  is_female   bmi  children  is_smoker     region  expenses
0      19          1  27.9         0          1  southwest  16884.92
1      18          0  33.8         1          0  southeast   1725.55
2      28          0  33.0         3          0  southeast   4449.46
3      33          0  22.7         0          0  northwest  21984.47
4      32          0  28.9         0          0  northwest   3866.86
...   ...        ...   ...       ...        ...        ...       ...
1333   50          0  31.0         3          0  northwest  10600.55
1334   18          1  31.9         0          0  northeast   2205.98
1335   18          1  36.9         0          0  southeast   1629.83
1336   21          1  25.8         0          0  southwest   2007.95
1337   61          1  29.1         0          1  northwest  29141.36

[1337 rows x 7 columns]

In [21]:
df['region'].value_counts()

region
southeast    364
southwest    325
northwest    324
northeast    324
Name: count, dtype: int64

In [22]:
#one hot encoding"
df= pd.get_dummies(df, columns=['region'], drop_first=True)

In [23]:
df

,age,is_female,bmi,children,is_smoker,expenses,region_northwest,region_southeast,region_southwest
0,19,1,27.9,0,1,16884.92,False,False,True
1,18,0,33.8,1,0,1725.55,False,True,False
2,28,0,33.0,3,0,4449.46,False,True,False
3,33,0,22.7,0,0,21984.47,True,False,False
4,32,0,28.9,0,0,3866.86,True,False,False
...,...,...,...,...,...,...,...,...,...
1333,50,0,31.0,3,0,10600.55,True,False,False
1334,18,1,31.9,0,0,2205.98,False,False,False
1335,18,1,36.9,0,0,1629.83,False,True,False
1336,21,1,25.8,0,0,2007.95,False,False,True
1337,61,1,29.1,0,1,29141.36,True,False,False

In [24]:
df =df.astype(int)
df.head()

,age,is_female,bmi,children,is_smoker,expenses,region_northwest,region_southeast,region_southwest
0,19,1,27,0,1,16884,0,0,1
1,18,0,33,1,0,1725,0,1,0
2,28,0,33,3,0,4449,0,1,0
3,33,0,22,0,0,21984,1,0,0
4,32,0,28,0,0,3866,1,0,0

# feature engineering and Extraction

In [25]:
df.head()

,age,is_female,bmi,children,is_smoker,expenses,region_northwest,region_southeast,region_southwest
0,19,1,27,0,1,16884,0,0,1
1,18,0,33,1,0,1725,0,1,0
2,28,0,33,3,0,4449,0,1,0
3,33,0,22,0,0,21984,1,0,0
4,32,0,28,0,0,3866,1,0,0

In [26]:
df['bmi_cetogory'] = pd.cut(
    df['bmi'],
    bins=[0,18.5,24.9,29.9, float("inf")],
    labels=['underweight','normal','overweight','obese']
        
)

In [27]:
df.head()

,age,is_female,bmi,children,is_smoker,expenses,region_northwest,region_southeast,region_southwest,bmi_cetogory
0,19,1,27,0,1,16884,0,0,1,overweight
1,18,0,33,1,0,1725,0,1,0,obese
2,28,0,33,3,0,4449,0,1,0,obese
3,33,0,22,0,0,21984,1,0,0,normal
4,32,0,28,0,0,3866,1,0,0,overweight

In [28]:
df.dtypes

age                    int64
is_female              int64
bmi                    int64
children               int64
is_smoker              int64
expenses               int64
region_northwest       int64
region_southeast       int64
region_southwest       int64
bmi_cetogory        category
dtype: object

In [29]:
df = pd.get_dummies(df,columns=['bmi_cetogory'],drop_first=True) #covert str to int

In [30]:
df.head(
)

,age,is_female,bmi,children,is_smoker,expenses,region_northwest,region_southeast,region_southwest,bmi_cetogory_normal,bmi_cetogory_overweight,bmi_cetogory_obese
0,19,1,27,0,1,16884,0,0,1,False,True,False
1,18,0,33,1,0,1725,0,1,0,False,False,True
2,28,0,33,3,0,4449,0,1,0,False,False,True
3,33,0,22,0,0,21984,1,0,0,True,False,False
4,32,0,28,0,0,3866,1,0,0,False,True,False

In [31]:
df =df.astype(int)
df.head()

,age,is_female,bmi,children,is_smoker,expenses,region_northwest,region_southeast,region_southwest,bmi_cetogory_normal,bmi_cetogory_overweight,bmi_cetogory_obese
0,19,1,27,0,1,16884,0,0,1,0,1,0
1,18,0,33,1,0,1725,0,1,0,0,0,1
2,28,0,33,3,0,4449,0,1,0,0,0,1
3,33,0,22,0,0,21984,1,0,0,1,0,0
4,32,0,28,0,0,3866,1,0,0,0,1,0

In [32]:
df['age_group'] = pd.cut(
    df['age'],
    bins=[0, 17, 34, 54, 100],
    labels=['0-17', '18-34', '35-54', '55+']
)

In [33]:
df.head()

,age,is_female,bmi,children,is_smoker,expenses,region_northwest,region_southeast,region_southwest,bmi_cetogory_normal,bmi_cetogory_overweight,bmi_cetogory_obese,age_group
0,19,1,27,0,1,16884,0,0,1,0,1,0,18-34
1,18,0,33,1,0,1725,0,1,0,0,0,1,18-34
2,28,0,33,3,0,4449,0,1,0,0,0,1,18-34
3,33,0,22,0,0,21984,1,0,0,1,0,0,18-34
4,32,0,28,0,0,3866,1,0,0,0,1,0,18-34

In [34]:
df = pd.get_dummies(df,columns=['age_group'],drop_first=True) #covert str to int

In [35]:
df =df.astype(int)

In [36]:
df.head()

,age,is_female,bmi,children,is_smoker,expenses,region_northwest,region_southeast,region_southwest,bmi_cetogory_normal,bmi_cetogory_overweight,bmi_cetogory_obese,age_group_18-34,age_group_35-54,age_group_55+
0,19,1,27,0,1,16884,0,0,1,0,1,0,1,0,0
1,18,0,33,1,0,1725,0,1,0,0,0,1,1,0,0
2,28,0,33,3,0,4449,0,1,0,0,0,1,1,0,0
3,33,0,22,0,0,21984,1,0,0,1,0,0,1,0,0
4,32,0,28,0,0,3866,1,0,0,0,1,0,1,0,0

Feature scaling

In [37]:
df.columns

Index(['age', 'is_female', 'bmi', 'children', 'is_smoker', 'expenses',
       'region_northwest', 'region_southeast', 'region_southwest',
       'bmi_cetogory_normal', 'bmi_cetogory_overweight', 'bmi_cetogory_obese',
       'age_group_18-34', 'age_group_35-54', 'age_group_55+'],
      dtype='str')

In [38]:
from sklearn.preprocessing import StandardScaler
cols=["age","bmi","children"]
scaler =StandardScaler()
df[cols] = scaler.fit_transform(df[cols])

In [39]:
df.head()

,age,is_female,bmi,children,is_smoker,expenses,region_northwest,region_southeast,region_southwest,bmi_cetogory_normal,bmi_cetogory_overweight,bmi_cetogory_obese,age_group_18-34,age_group_35-54,age_group_55+
0,-1.440418,1,-0.524321,-0.909234,1,16884,0,0,1,0,1,0,1,0,0
1,-1.511647,0,0.457496,-0.079442,0,1725,0,1,0,0,0,1,1,0,0
2,-0.799350,0,0.457496,1.580143,0,4449,0,1,0,0,0,1,1,0,0
3,-0.443201,0,-1.342502,-0.909234,0,21984,1,0,0,1,0,0,1,0,0
4,-0.514431,0,-0.360685,-0.909234,0,3866,1,0,0,0,1,0,1,0,0

In [40]:
df.dtypes

age                        float64
is_female                    int64
bmi                        float64
children                   float64
is_smoker                    int64
expenses                     int64
region_northwest             int64
region_southeast             int64
region_southwest             int64
bmi_cetogory_normal          int64
bmi_cetogory_overweight      int64
bmi_cetogory_obese           int64
age_group_18-34              int64
age_group_35-54              int64
age_group_55+                int64
dtype: object

# Feature Extraction

In [41]:
from scipy.stats import pearsonr


# List of features to check against target
selected_features = [
    'age', 'bmi', 'children', 'is_female', 'is_smoker',
    'region_northwest', 'region_southeast', 'region_southwest',
    'bmi_cetogory_normal', 'bmi_cetogory_overweight', 'bmi_cetogory_obese','age_group_18-34','age_group_35-54','age_group_55+'
]

correlations = {
    feature: pearsonr(df[feature], df['expenses'])[0]
    for feature in selected_features
}
correlation_df = pd.DataFrame(list(correlations.items()), columns=['Feature', 'Pearson Correlation'])
correlation_df.sort_values(by='Pearson Correlation', ascending=False)

                    Feature  Pearson Correlation
4                 is_smoker             0.787234
0                       age             0.298309
13            age_group_55+             0.203261
10       bmi_cetogory_obese             0.200347
1                       bmi             0.197714
12          age_group_35-54             0.088124
6          region_southeast             0.073577
2                  children             0.067390
5          region_northwest            -0.038695
7          region_southwest            -0.043637
3                 is_female            -0.058046
8       bmi_cetogory_normal            -0.104283
9   bmi_cetogory_overweight            -0.120595
11          age_group_18-34            -0.247225

In [42]:
categorical_cols = [
    'is_smoker',
    'is_female',
    'age_group_18-34',
    'age_group_35-54',
    'age_group_55+',
    'bmi_cetogory_normal',
    'bmi_cetogory_overweight',
    'bmi_cetogory_obese',
    'region_southeast',
    'region_northwest',
    'region_southwest'
]

In [43]:
from scipy.stats import chi2_contingency
import pandas as pd

alpha = 0.05

df['charges_bin'] = pd.qcut(df['expenses'], q=4, labels=False)
chi2_results = {}

for col in categorical_cols:
    contingency = pd.crosstab(df[col], df['charges_bin'])
    chi2_stat, p_val, _, _ = chi2_contingency(contingency)
    decision = 'Reject Null (Keep Feature)' if p_val < alpha else 'Accept Null (Drop Feature)'
    chi2_results[col] = {
        'chi2_statistic': chi2_stat,
        'p_value': p_val,
        'Decision': decision
    }

chi2_df = pd.DataFrame(chi2_results).T
chi2_df = chi2_df.sort_values(by='p_value')
chi2_df

                        chi2_statistic   p_value                    Decision
is_smoker                   848.219178       0.0  Reject Null (Keep Feature)
age_group_18-34             675.147466       0.0  Reject Null (Keep Feature)
age_group_35-54             464.575733       0.0  Reject Null (Keep Feature)
age_group_55+               446.231518       0.0  Reject Null (Keep Feature)
region_southeast             15.998167  0.001135  Reject Null (Keep Feature)
is_female                    10.258784   0.01649  Reject Null (Keep Feature)
bmi_cetogory_obese            8.515711  0.036473  Reject Null (Keep Feature)
region_southwest              5.091893  0.165191  Accept Null (Drop Feature)
bmi_cetogory_overweight       4.873307  0.181313  Accept Null (Drop Feature)
bmi_cetogory_normal           4.231793  0.237498  Accept Null (Drop Feature)
region_northwest               1.13424  0.768815  Accept Null (Drop Feature)

In [44]:

final_df = df[['age_group_18-34','age_group_35-54','age_group_55+', 'is_female', 'bmi', 'children', 'is_smoker', 'expenses','region_southeast','bmi_cetogory_obese']]

In [55]:
final_df

,age_group_18-34,age_group_35-54,age_group_55+,is_female,bmi,children,is_smoker,expenses,region_southeast,bmi_cetogory_obese
0,1,0,0,1,-0.524321,-0.909234,1,16884,0,0
1,1,0,0,0,0.457496,-0.079442,0,1725,1,1
2,1,0,0,0,0.457496,1.580143,0,4449,1,1
3,1,0,0,0,-1.342502,-0.909234,0,21984,0,0
4,1,0,0,0,-0.360685,-0.909234,0,3866,0,0
...,...,...,...,...,...,...,...,...,...,...
1333,0,1,0,0,0.130224,1.580143,0,10600,0,1
1334,1,0,0,1,0.130224,-0.909234,0,2205,0,1
1335,1,0,0,1,0.948405,-0.909234,0,1629,1,1
1336,1,0,0,1,-0.851594,-0.909234,0,2007,0,0
1337,0,0,1,1,-0.197049,-0.909234,1,29141,0,0

In [48]:
# Save the updated DataFrame to a new CSV file
final_df.to_csv("insurance_updated.csv", index=False)