# Data cleaning  &Pre Processing

In [4]:
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
import warnings
warnings.filterwarnings("ignore")

In [30]:
df = pd.read_csv("insurance (1).csv")
df

      age     sex   bmi  children smoker     region  expenses
0      19  female  27.9         0    yes  southwest  16884.92
1      18    male  33.8         1     no  southeast   1725.55
2      28    male  33.0         3     no  southeast   4449.46
3      33    male  22.7         0     no  northwest  21984.47
4      32    male  28.9         0     no  northwest   3866.86
...   ...     ...   ...       ...    ...        ...       ...
1333   50    male  31.0         3     no  northwest  10600.55
1334   18  female  31.9         0     no  northeast   2205.98
1335   18  female  36.9         0     no  southeast   1629.83
1336   21  female  25.8         0     no  southwest   2007.95
1337   61  female  29.1         0    yes  northwest  29141.36

[1338 rows x 7 columns]

In [31]:
df.head()

   age     sex   bmi  children smoker     region  expenses
0   19  female  27.9         0    yes  southwest  16884.92
1   18    male  33.8         1     no  southeast   1725.55
2   28    male  33.0         3     no  southeast   4449.46
3   33    male  22.7         0     no  northwest  21984.47
4   32    male  28.9         0     no  northwest   3866.86

In [32]:
df.shape

(1338, 7)

In [33]:
df.isnull().sum()

age         0
sex         0
bmi         0
children    0
smoker      0
region      0
expenses    0
dtype: int64

In [34]:
df.drop_duplicates(inplace=True)
df.shape

(1337, 7)

In [35]:
df.dtypes

age           int64
sex             str
bmi         float64
children      int64
smoker          str
region          str
expenses    float64
dtype: object

In [36]:
df['sex'].unique()

<ArrowStringArray>
['female', 'male']
Length: 2, dtype: str

In [37]:
#convert str to int
#labeled encoding
df['sex']= df["sex"].map({"male":0 , "female": 1})

In [38]:
df.dtypes

age           int64
sex           int64
bmi         float64
children      int64
smoker          str
region          str
expenses    float64
dtype: object

In [39]:
df.head()

   age  sex   bmi  children smoker     region  expenses
0   19    1  27.9         0    yes  southwest  16884.92
1   18    0  33.8         1     no  southeast   1725.55
2   28    0  33.0         3     no  southeast   4449.46
3   33    0  22.7         0     no  northwest  21984.47
4   32    0  28.9         0     no  northwest   3866.86

In [40]:
df['smoker'].unique()

<ArrowStringArray>
['yes', 'no']
Length: 2, dtype: str

In [43]:
df['smoker'].value_counts()

smoker
0    1063
1     274
Name: count, dtype: int64

In [41]:
df['smoker']= df['smoker'].map({'yes':1,'no':0})
df.dtypes

age           int64
sex           int64
bmi         float64
children      int64
smoker        int64
region          str
expenses    float64
dtype: object

In [42]:
df.head()

   age  sex   bmi  children  smoker     region  expenses
0   19    1  27.9         0       1  southwest  16884.92
1   18    0  33.8         1       0  southeast   1725.55
2   28    0  33.0         3       0  southeast   4449.46
3   33    0  22.7         0       0  northwest  21984.47
4   32    0  28.9         0       0  northwest   3866.86

In [44]:
#rename column
df.rename(columns={
    'sex': "is_female",
    'smoker':"is_smoker"
},inplace=True)

In [45]:
df

      age  is_female   bmi  children  is_smoker     region  expenses
0      19          1  27.9         0          1  southwest  16884.92
1      18          0  33.8         1          0  southeast   1725.55
2      28          0  33.0         3          0  southeast   4449.46
3      33          0  22.7         0          0  northwest  21984.47
4      32          0  28.9         0          0  northwest   3866.86
...   ...        ...   ...       ...        ...        ...       ...
1333   50          0  31.0         3          0  northwest  10600.55
1334   18          1  31.9         0          0  northeast   2205.98
1335   18          1  36.9         0          0  southeast   1629.83
1336   21          1  25.8         0          0  southwest   2007.95
1337   61          1  29.1         0          1  northwest  29141.36

[1337 rows x 7 columns]

In [47]:
df['region'].value_counts()

region
southeast    364
southwest    325
northwest    324
northeast    324
Name: count, dtype: int64

In [48]:
#one hot encoding
df= pd.get_dummies(df, columns=['region'], drop_first=True)

In [49]:
df

,age,is_female,bmi,children,is_smoker,expenses,region_northwest,region_southeast,region_southwest
0,19,1,27.9,0,1,16884.92,False,False,True
1,18,0,33.8,1,0,1725.55,False,True,False
2,28,0,33.0,3,0,4449.46,False,True,False
3,33,0,22.7,0,0,21984.47,True,False,False
4,32,0,28.9,0,0,3866.86,True,False,False
...,...,...,...,...,...,...,...,...,...
1333,50,0,31.0,3,0,10600.55,True,False,False
1334,18,1,31.9,0,0,2205.98,False,False,False
1335,18,1,36.9,0,0,1629.83,False,True,False
1336,21,1,25.8,0,0,2007.95,False,False,True
1337,61,1,29.1,0,1,29141.36,True,False,False

In [51]:
df =df.astype(int)
df.head()

,age,is_female,bmi,children,is_smoker,expenses,region_northwest,region_southeast,region_southwest
0,19,1,27,0,1,16884,0,0,1
1,18,0,33,1,0,1725,0,1,0
2,28,0,33,3,0,4449,0,1,0
3,33,0,22,0,0,21984,1,0,0
4,32,0,28,0,0,3866,1,0,0