In [4]:
import numpy as np
import pandas as pd

In [5]:
df = pd.read_csv(r'anime.csv')
df.head()

   Rank                                              Title  Score
0     1  Fullmetal Alchemist: BrotherhoodTV (64 eps)Apr...   9.10
1     2  Steins;GateTV (24 eps)Apr 2011 - Sep 20112,473...   9.07
2     3  Bleach: Sennen Kessen-henTV (13 eps)Oct 2022 -...   9.06
3     4  Gintama°TV (51 eps)Apr 2015 - Mar 2016605,113 ...   9.06
4     5  Shingeki no Kyojin Season 3 Part 2TV (10 eps)A...   9.05

In [6]:
#make a new column for episode count
#make a new column for time stamp
#which anime has the highest score
#give me top 5 highest scoring anime
#which anime has the highest episode count
#animes with top 5 episode count
#which is the longest running anime

In [7]:
df.loc[1]

Rank                                                     2
Title    Steins;GateTV (24 eps)Apr 2011 - Sep 20112,473...
Score                                                 9.07
Name: 1, dtype: object

In [8]:
df.loc[2]['Title']

'Bleach: Sennen Kessen-henTV (13 eps)Oct 2022 - Dec 2022474,138 members'

In [9]:
#make a new column for episode count
def extraction_episodes(txt):
    check =False
    data =""
    for i in txt:
        if i == ")":
            check= False
            return data
        if check ==True:
             data = data + i
        if i =="(":
             check = True

In [10]:
df["Episodes"]=df["Title"].apply(extraction_episodes)

In [11]:
df["Episodes"]= df["Episodes"].str.replace(" eps", "")

In [12]:
type(df.loc[0]["Episodes"])

str

In [13]:
#convert into int
df["Episodes"]=df['Episodes'].astype(int)

In [ ]:
#make a new column for time stamp

In [16]:
df.loc[3]['Title']

'Gintama°TV (51 eps)Apr 2015 - Mar 2016605,113 members'

In [17]:
def extraction_time(txt):
    check =False
    data =""
    for i in range(len(txt)):
        if txt[i]==')':
            for j in range(i+1, i+20):
                data +=txt[j]

            return data

In [20]:
df['Total time'] = df['Title'].apply(extraction_time)
df.head()

,Rank,Title,Score,Episodes,Total time
0,1,Fullmetal Alchemist: BrotherhoodTV (64 eps)Apr...,9.10,64,Apr 2009 - Jul 2010
1,2,"Steins;GateTV (24 eps)Apr 2011 - Sep 20112,473...",9.07,24,Apr 2011 - Sep 2011
2,3,Bleach: Sennen Kessen-henTV (13 eps)Oct 2022 -...,9.06,13,Oct 2022 - Dec 2022
3,4,"Gintama°TV (51 eps)Apr 2015 - Mar 2016605,113 ...",9.06,51,Apr 2015 - Mar 2016
4,5,Shingeki no Kyojin Season 3 Part 2TV (10 eps)A...,9.05,10,Apr 2019 - Jul 2019

In [29]:
import re

def extract_months(text):
    # Extract date range like "Apr 2009 - Jul 2010"
    match = re.search(r'([A-Za-z]{3}\s\d{4})\s*-\s*([A-Za-z]{3}\s\d{4})', str(text))

    if match:
        start = pd.to_datetime(match.group(1), format="%b %Y")
        end = pd.to_datetime(match.group(2), format="%b %Y")

        # Total months (inclusive)
        return (end.year - start.year) * 12 + (end.month - start.month) + 1

    return None

In [44]:
df["Months"] = df["Title"].apply(extract_months)

df.head()

,Rank,Title,Score,Episodes,Total time,Months
0,1,Fullmetal Alchemist: BrotherhoodTV (64 eps)Apr...,9.10,64,Apr 2009 - Jul 2010,16
1,2,"Steins;GateTV (24 eps)Apr 2011 - Sep 20112,473...",9.07,24,Apr 2011 - Sep 2011,6
2,3,Bleach: Sennen Kessen-henTV (13 eps)Oct 2022 -...,9.06,13,Oct 2022 - Dec 2022,3
3,4,"Gintama°TV (51 eps)Apr 2015 - Mar 2016605,113 ...",9.06,51,Apr 2015 - Mar 2016,12
4,5,Shingeki no Kyojin Season 3 Part 2TV (10 eps)A...,9.05,10,Apr 2019 - Jul 2019,4

In [56]:
#which anime has the highest score
df[df['Score'] == df['Score'].max()]['Title']

0    Fullmetal Alchemist: BrotherhoodTV (64 eps)Apr...
Name: Title, dtype: object

In [ ]:
#give me top 5 highest scoring anime



df["Title"].head()

0    Fullmetal Alchemist: BrotherhoodTV (64 eps)Apr...
1    Steins;GateTV (24 eps)Apr 2011 - Sep 20112,473...
2    Bleach: Sennen Kessen-henTV (13 eps)Oct 2022 -...
3    Gintama°TV (51 eps)Apr 2015 - Mar 2016605,113 ...
4    Shingeki no Kyojin Season 3 Part 2TV (10 eps)A...
Name: Title, dtype: object

In [60]:
#which anime has the highest episode count
df[df['Episodes'] ==df['Episodes'].max()]

,Rank,Title,Score,Episodes,Total time,Months
15,16,"GintamaTV (201 eps)Apr 2006 - Mar 20101,034,41...",8.94,201,Apr 2006 - Mar 2010,48

In [80]:
#animes with top 5 episode count
df['Episodes'].sort_values(ascending=False).head()

15    201
7     148
11    110
42     75
24     74
Name: Episodes, dtype: int64

In [84]:
#which is the longest running anime
df['Episodes'].max()

201

In [85]:
df.loc[df["Episodes"].idxmax(), [ "Episodes"]]

Episodes    201
Name: 15, dtype: object